#page title
page_title                                : Invi, Your Shopping friend                                  

# App Info

playstore_link                            :                                           
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo_invi.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Invi                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Invi is a mobile application which allows users to self-checkout using their smartphone. Invi also enables clubs or stores to track their equipment using Qr Code tags. Invi aims to reduce ques, and improve shopping and retning experience.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bartlomiej Mlynarkiewicz                          
your_city                                 : Limerick                                



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Qr Code / EAN-13 Scanner
    description                           : 
    fontawesome_icon_name                 : qrcode
    
  - title                                 : Store Receipts on Your Phone
    description                           : 
    fontawesome_icon_name                 : receipt

  - title                                 : Register Using Your Soical Media
    description                           : 
    fontawesome_icon_name                 : google

  - title                                 : Check Stores Based on Locality
    description                           : 
    fontawesome_icon_name                 : map-marker-alt

  - title                                 : Check Latest Conversion Rates
    description                           : 
    fontawesome_icon_name                 : sync
  
  - title                                 : Search for Products
    description                           : 
    fontawesome_icon_name                 : search

  - title                                 : Check Product Prices
    description                           : 
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Cart Total Automatically Converted
    description                           : 
    fontawesome_icon_name                 : sync

  - title                                 : Summary of Purchases
    description                           : 
    fontawesome_icon_name                 : chart-pie

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown